### ISSUE TITLE
German translation won't install

### ISSUE THREAD

**Issue by SiriusVI87** [GwendolyneFreddy/The_Minotaur_and_Lilacor#2]
There is a bug with the german language translation of this mod. In the slandor.tp2 it says:
 

LANGUAGE ~Deutsch (Uebersetzung von Gerri)~
         ~**deutsch**~
~slandor/lang/german/setup.tra~

but it should say:

LANGUAGE ~Deutsch (Uebersetzung von Gerri)~
         ~**german**~
~slandor/lang/german/setup.tra~

**Comment by Gitjas** [comment]
Thanks, fixed in master.
